### ISSUE TITLE
Add Notes entry sorting

### ISSUE THREAD

**Issue by MariTheAlien** [idispatch75/mythic-gme-adventures#20]
Hello! I've recently started using this app for Mythic 2E. It would be great if there were some way to order and sort the entries on the lists at the bottom of the dashboard (not the rollable Threads and Characters List). I keep a lot of notes, and the lack of sorting is something that's stopping me from keeping every aspect about an Adventure on the program itself.

**Comment by idispatch75** [comment]
Good idea.
I think I'll extend this to some other lists in the "management" section while I'm at it.

Do you think a long press on the item to start dragging is discoverable enough, or should I display a small handle on each item that you have to press to start dragging?

**Comment by idispatch75** [comment]
To reply to my own question: using a handle is OK. It does not take that much space.

![image](https://github.com/user-attachments/assets/4e1a4b11-dc42-4a07-bc7a-916a238e9676)

![image](https://github.com/user-attachments/assets/318be6ec-b836-44fd-ab66-8dad0a14a3ac)

**Comment by MariTheAlien** [comment]
Oh yeah, that handle looks much like what I would expect from the mobile app. I mainly use the PC program, but having this type of handle on there too would definitely be better than nothing.

**Comment by idispatch75** [comment]
Implemented in https://github.com/idispatch75/mythic-gme-adventures/releases/tag/v1.7.0

Feel free to create other issues for usability improvements, even minor. I don't promise I'll implement them all though :).
