### ISSUE TITLE
Add dice roll presets

### ISSUE THREAD

**Issue by idispatch75** [idispatch75/mythic-gme-adventures#8]

**Comment by redhoar** [comment]
Presets like 1D10, 1D100 (Location Crafter)
Also, a flag (box?) to check against Chaos on 1D100

**Comment by idispatch75** [comment]
I don't know Location Crafter.
I'm not sure I understand what you suggest. Is it presets of possible dice rolls for a game system for instance (for example, if you play D&D you'll need to roll 1d20+y and xd6+y and xd8+y and xd10+y only, so these rolls will be made more accessible in some way. And if you change your game system, then you'll have another set of often used rolls.

Or do you want to roll on different tables as you do for meaning tables.

What do you mean by "roll against Chaos". Is it the Chaos factor? It is a number between 1 and 9. How can you roll 1d100 against it?
